### ISSUE TITLE
Cases where users used a different prefix instead of "CAB-"

### ISSUE THREAD

**Issue by ghost** [IllusionMods/Unity3DCompressor#2]
Hello.
If users use a random prefix instead of CAB-, like FTB-,XXX-, CABRandomization process seems to be skipped.
I want to randomize the CAB-string of a very large number of assetbundle files so that there is no conflict.
How do I modify the code to correct this random first 4 letter prefix to CAB- and perform CABRandomization?
Thank you.

**Comment by ManlyMarco** [comment]
There's no easy fix, you have to match the cab string one way or another if you want to randomize it. Why do you want to randomize the cab string anyways? Can't you keep the old ones?

**Comment by ghost** [comment]
When checking the ABs of my game with SB3U, I found that many user mod Assetbundles have duplicate Cab-strings.
The games I'm using don't have sideloader. so mods are hard mods.
So I thought these duplicate Cab-strings could potentially cause problems.
And in terms of management, I've been wanting to remove all these duplicates or incorrect Cab-strings. 
Then the orderly state will make me feel good ^_<
Anyway, I manually corrected the ABs with the wrong prefix.
It would be nice if it could be automated with a program tho, but you said that it is not an easy task, and since such incorrect prefixes do not account for a large percentage, it is not difficult to manage them manually.

Thank you for answering! I am always grateful for your Dev work
